[package]
name = "auto-note"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27"
egui = "0.27"
enigo = "0.1"
rdev = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
